# Generated by Django 6.1 on 2026-09-02 16:47

import chalani.models
import django.db.models.deletion
import nepal.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orgs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chalani",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chalani_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="चलानी नं."
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="मिति (ई.सं.)"),
                ),
                (
                    "date_bs",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="मिति (बि.सं.)"
                    ),
                ),
                (
                    "fiscal_year",
                    models.CharField(
                        blank=True, db_index=True, max_length=9, verbose_name="आ.व."
                    ),
                ),
                (
                    "vehicle_no",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        validators=[nepal.validators.validate_vehicle_no],
                        verbose_name="गाडी नं.",
                    ),
                ),
                (
                    "received_by",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="बुझिलिनेको नाम"
                    ),
                ),
                (
                    "remarks",
                    models.CharField(blank=True, max_length=300, verbose_name="कैफियत"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to=chalani.models.chalani_upload_path
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("extracting", "प्रशोधन हुँदै (Extracting)"),
                            ("draft", "मस्यौदा (Draft)"),
                            ("verified", "प्रमाणित (Verified)"),
                            ("billed", "बिल भयो (Billed)"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("extracted_by_ai", models.BooleanField(default=False)),
                ("raw_extraction", models.JSONField(blank=True, null=True)),
                ("extraction_error", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chalanis_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="orgs.organization",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chalanis_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Item name")),
                (
                    "name_np",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="सामानको नाम"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "थान (Pieces)"),
                            ("bag", "बोरा (Bag / Sack)"),
                            ("kg", "के.जी. (Kilogram)"),
                            ("quintal", "क्विन्टल (Quintal)"),
                            ("ton", "टन (Metric ton)"),
                            ("ltr", "लिटर (Litre)"),
                            ("m", "मिटर (Metre)"),
                            ("rft", "रनिङ फिट (Running foot)"),
                            ("sqft", "वर्ग फिट (Square foot)"),
                            ("cft", "घन फिट (Cubic foot)"),
                            ("cum", "घन मिटर (Cubic metre)"),
                            ("trip", "ट्रिप (Trip / Load)"),
                            ("bundle", "बन्डल (Bundle)"),
                            ("roll", "रोल (Roll)"),
                            ("dozen", "दर्जन (Dozen)"),
                            ("packet", "प्याकेट (Packet)"),
                            ("carton", "कार्टुन (Carton)"),
                            ("set", "सेट (Set)"),
                            ("pair", "जोर (Pair)"),
                            ("sheet", "पाता (Sheet)"),
                        ],
                        default="pcs",
                        max_length=20,
                        verbose_name="इकाई",
                    ),
                ),
                (
                    "default_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="सामान्य दर",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "search_key",
                    models.CharField(blank=True, db_index=True, max_length=420),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="orgs.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ChalaniItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="कागजमा लेखिएको"),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="परिमाण"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "थान (Pieces)"),
                            ("bag", "बोरा (Bag / Sack)"),
                            ("kg", "के.जी. (Kilogram)"),
                            ("quintal", "क्विन्टल (Quintal)"),
                            ("ton", "टन (Metric ton)"),
                            ("ltr", "लिटर (Litre)"),
                            ("m", "मिटर (Metre)"),
                            ("rft", "रनिङ फिट (Running foot)"),
                            ("sqft", "वर्ग फिट (Square foot)"),
                            ("cft", "घन फिट (Cubic foot)"),
                            ("cum", "घन मिटर (Cubic metre)"),
                            ("trip", "ट्रिप (Trip / Load)"),
                            ("bundle", "बन्डल (Bundle)"),
                            ("roll", "रोल (Roll)"),
                            ("dozen", "दर्जन (Dozen)"),
                            ("packet", "प्याकेट (Packet)"),
                            ("carton", "कार्टुन (Carton)"),
                            ("set", "सेट (Set)"),
                            ("pair", "जोर (Pair)"),
                            ("sheet", "पाता (Sheet)"),
                        ],
                        default="pcs",
                        max_length=20,
                        verbose_name="इकाई",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="दर",
                    ),
                ),
                ("line_no", models.PositiveSmallIntegerField(default=0)),
                (
                    "chalani",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="chalani.chalani",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chalani_lines",
                        to="chalani.item",
                    ),
                ),
            ],
            options={
                "ordering": ["line_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Supplier name"),
                ),
                (
                    "name_np",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="आपूर्तिकर्ताको नाम"
                    ),
                ),
                (
                    "pan_no",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[nepal.validators.validate_pan],
                        verbose_name="PAN/VAT",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[nepal.validators.validate_nepali_phone],
                        verbose_name="फोन",
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, verbose_name="ठेगाना"),
                ),
                (
                    "district",
                    models.CharField(blank=True, max_length=60, verbose_name="जिल्ला"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "search_key",
                    models.CharField(blank=True, db_index=True, max_length=420),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="orgs.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="chalani",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chalanis",
                to="chalani.vendor",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["organization", "name"], name="chalani_ite_organiz_ce2f1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["organization", "name"], name="chalani_ven_organiz_f8eb61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chalani",
            index=models.Index(
                fields=["organization", "-date"], name="chalani_cha_organiz_410346_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chalani",
            index=models.Index(
                fields=["organization", "status"], name="chalani_cha_organiz_529199_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chalani",
            index=models.Index(
                fields=["organization", "fiscal_year"],
                name="chalani_cha_organiz_85c687_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chalani",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["verified", "billed"]),
                    models.Q(("chalani_no", ""), _negated=True),
                ),
                fields=("organization", "vendor", "chalani_no"),
                name="unique_verified_chalani",
            ),
        ),
    ]
