# Generated by Django 6.1 on 2026-09-02 16:47

import django.db.models.deletion
import nepal.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Firm name")),
                (
                    "name_np",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="फर्मको नाम"
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "pan_no",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[nepal.validators.validate_pan],
                        verbose_name="PAN/VAT",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[nepal.validators.validate_nepali_phone],
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, verbose_name="ठेगाना"),
                ),
                (
                    "district",
                    models.CharField(blank=True, max_length=60, verbose_name="जिल्ला"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "मालिक (Owner)"),
                            ("manager", "म्यानेजर (Manager)"),
                            ("staff", "कर्मचारी (Staff)"),
                        ],
                        default="staff",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="orgs.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["organization__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "user"), name="unique_org_membership"
                    )
                ],
            },
        ),
    ]
